local-zone: "dds.microsoft.com" always_nxdomain
local-zone: "fd.dds.microsoft.com" always_nxdomain
local-zone: "aad.cs.dds.microsoft.com" always_nxdomain
local-zone: "cdpcs.access.microsoft.com" always_nxdomain
local-zone: "geo.prod.do.dsp.mp.microsoft.com" always_nxdomain
local-zone: "activity.windows.com" always_nxdomain
local-zone: "cdn.activity.windows.com" always_nxdomain
local-zone: "telemetry.microsoft.com" always_nxdomain
local-zone: "telemetry.microsoft.us" always_nxdomain
local-zone: "watson.telemetry.microsoft.com" always_nxdomain
local-zone: "watson2.alpha.telemetry.microsoft.com" always_nxdomain
local-zone: "watson7.alpha.telemetry.microsoft.com" always_nxdomain
local-zone: "wer.alpha.telemetry.microsoft.com" always_nxdomain
local-zone: "oca.telemetry.microsoft.us" always_nxdomain
local-zone: "umwatsonc.telemetry.microsoft.us" always_nxdomain
local-zone: "telemetry.microsoft.com.nsatc.net" always_nxdomain
local-zone: "events.data.microsoft.com" always_nxdomain
local-zone: "eu-r-office.events.data.microsoft.com" always_nxdomain
local-zone: "us-ic3.events.data.microsoft.com" always_nxdomain
local-zone: "dnsbl.test.watson.events.data.microsoft.com" always_nxdomain
local-zone: "fp.measure.office.com" always_nxdomain
local-zone: "logging.windows.microsoft.com" always_nxdomain
local-zone: "storagetos.datamart.windows.com" always_nxdomain
local-zone: "wustat.windows.com" always_nxdomain
local-zone: "db5p.notify.windows.com" always_nxdomain
local-zone: "engage.windows.com" always_nxdomain