powershell -nop -c "Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Cryptography' -Name 'MachineGuid' -Value ([guid]::NewGuid().ToString()) -Force" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography' GUID ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Get-NetAdapter | %% { Set-NetAdapter -Name $_.Name -MacAddress (((1..6|%%{'{0:X2}' -f (Get-Random 256)})-join '-')) -Confirm:$false -ErrorAction SilentlyContinue }" >nul 2>&1
powershell -nop -ex bypass -c "$mac=(-join((1..6)|%%{'{0:X2}' -f (Get-Random 256)})); $base='HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002bE10318}'; Get-ChildItem $base -EA SilentlyContinue | ForEach-Object { if((Get-ItemProperty $_.PSPath -Name NetCfgInstanceId -EA SilentlyContinue).NetCfgInstanceId){ Set-ItemProperty $_.PSPath NetworkAddress $mac -Force -EA SilentlyContinue } }; Set-NetAdapterAdvancedProperty -Name '*' -RegistryKeyword 'NetworkAddress' -RegistryValue $mac -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "$cv='HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'; Set-ItemProperty $cv RegisteredOwner ('User'+(Get-Random -Max 999999)); Set-ItemProperty $cv InstallDate ([int](Get-Date (Get-Date).AddDays(-(Get-Random -Min 30 -Max 730)) -UFormat %%s))" >nul 2>&1
powershell -nop -ex bypass -c "$d=(Get-Date).AddDays(-(Get-Random -Min 30 -Max 730)).ToFileTime(); $b=[System.BitConverter]::GetBytes([long]$d); Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' InstallTime $b" >nul 2>&1
powershell -nop -ex bypass -c "$cv='HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'; $p={-join((1..5)|%%{Get-Random -Max 10})}; Set-ItemProperty $cv ProductId ((&$p)+'-'+(&$p)+'-'+(&$p)+'-'+(&$p))" >nul 2>&1
powershell -nop -ex bypass -c "$v='C:\Program Files (x86)\VolumeID\Volumeid64.exe'; foreach($d in 'C','D','E','F','G'){ & $v ($d + ':\') ((-join((1..2)|%%{'{0:X2}' -f (Get-Random 256)}))+'-'+(-join((1..2)|%%{'{0:X2}' -f (Get-Random 256)}))) }" >nul 2>&1
powershell -nop -ex bypass -c "$h='DESKTOP-'+(-join((1..7)|%%{([char[]]'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'|Get-Random)})); Rename-Computer -NewName $h -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' Hostname $h -Force; Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' 'NV Hostname' $h -Force" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' Domain (-join((1..8)|%%{([char[]]'abcdefghijklmnopqrstuvwxyz'|Get-Random)})+'.local') -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\SystemInformation' ComputerHardwareId ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\SystemInformation' ComputerHardwareIds ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\BasicDisplay\Video' VideoID ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Tracing\Microsoft\Profile\Profile' Guid ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKCU:\Software\Microsoft\Direct3D' WHQLClass ([byte[]](1..64|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "$base='HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'; Get-ChildItem $base -EA SilentlyContinue | ForEach-Object { $d=(Get-ItemProperty $_.PSPath -Name DriverDesc -EA SilentlyContinue).DriverDesc; if($d -like '*NVIDIA*'){ Set-ItemProperty $_.PSPath _DriverProviderInfo ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue; Set-ItemProperty $_.PSPath UserModeDriverGUID ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue } }" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\SQMClient\Windows' MachineId ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\SQMClient' MachineId ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\SQMClient' UserId ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting' MachineID ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate' SusClientId ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate' SusClientIdValidation ([byte[]](1..32|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\SQMClient' WinSqmFirstSessionStartTime ([byte[]](1..8|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\IDConfigDB\Hardware Profiles\0001' HwProfileGuid ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\IDConfigDB\Hardware Profiles\0001' GUID ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKCU:\Printers\Defaults' NetID ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "$id=[guid]::NewGuid().ToString(); Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo' Id $id -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\AdvertisingInfo' Id $id -Force -EA SilentlyContinue; Set-ItemProperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo' Id $id -Force -EA SilentlyContinue; Set-ItemProperty 'Registry::HKEY_USERS\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo' Id $id -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' DigitalProductId ([byte[]](1..164|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' DigitalProductId4 ([byte[]](1..1272|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform\Activation' ProductActivationTime ([byte[]](1..8|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate' AccountDomainSid ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate' PingID ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\NVIDIA Corporation\Global' ClientUUID ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\NVIDIA Corporation\Global' PersistenceIdentifier ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue; Set-ItemProperty 'HKLM:\SOFTWARE\NVIDIA Corporation\Global\CoProcManager' ChipsetMatchID ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "$base='HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002bE10318}'; Get-ChildItem $base -EA SilentlyContinue | ForEach-Object { if((Get-ItemProperty $_.PSPath -Name NetCfgInstanceId -EA SilentlyContinue).NetCfgInstanceId){ Set-ItemProperty $_.PSPath NetworkInterfaceInstallTimestamp ([byte[]](1..8|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue } }" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\TPM\WMI' WindowsAIKHash ([byte[]](1..32|%%{Get-Random -Max 256})) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' RegisteredOrganization (-join((1..6)|%%{([char[]]'ABCDEFGHIJKLMNOPQRSTUVWXYZ'|Get-Random)})) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "New-Item -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\DevQuery\6' -Force -EA SilentlyContinue | Out-Null; Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\DevQuery\6' UUID ([guid]::NewGuid().ToString()) -Force -EA SilentlyContinue" >nul 2>&1
powershell -nop -ex bypass -c "Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WINEVT\Channels\Microsoft-Windows-Kernel-EventTracing/Admin' OwningPublisher ('{'+[guid]::NewGuid().ToString()+'}') -Force -EA SilentlyContinue" >nul 2>&1
exit
