@echo off
:: Generated by ApplyRWE-AMD.ps1 on 2026-05-27 03:03
:: IMOD Interval + RWE Tweaks

:: --- RWEverything Tweaks ---
cd /d "C:\Program Files\RW-Everything"

Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A1024 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A1044 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A1064 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A1084 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A10A4 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A10C4 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A10E4 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF66A1104 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0x7FF2020024 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF62004E4 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF6200504 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF6200524 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF6200544 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF6200564 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF6200584 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF62005A4 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xF62005C4 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="WRMSR 0xC001102B 0x00000000 0x2000CC14"
Rw.exe /Min /NoLogo /Stdout /Command="WRMSR 0xC0010296 0x00000000 0x00080808"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xFED00010 0x0"
Rw.exe /Min /NoLogo /Stdout /Command="W16 0xF0E2 0x0008"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xFEE003E0 0x0000000B"
Rw.exe /Min /NoLogo /Stdout /Command="W32 0xFEE00080 0x00000000"

exit /b 0
